### ISSUE TITLE
Attribute version is not allowed here in XML

### ISSUE THREAD

**Issue by NaokiTsuchiya** [alps-io/schemas#7]
[In the spec](https://datatracker.ietf.org/doc/html/draft-amundsen-richardson-foster-alps-07#section-2.3.2.1), `version` is an attribute of `alps` element.

Here is an error in IDE.

![image](https://user-images.githubusercontent.com/17171732/119093425-a8f66b80-ba4a-11eb-9494-53dc01806903.png)

**Comment by koriym** [comment]
@NaokiTsuchiya Thanks. It would be nice to have a PR.😀

**Comment by NaokiTsuchiya** [comment]
@koriym Fixed #8
